// Node-only codegen for the regions registry. SERVER ONLY — never import from client code.
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { RegionPoly } from "@/lib/maps/regions";

function regionsDir(): string {
  return join(process.cwd(), "lib", "maps", "regions");
}

// Write a single map's regions to lib/maps/regions/<map-lowercased>.json.
export async function writeMapRegions(
  map: string,
  regions: RegionPoly[],
): Promise<void> {
  const file = join(regionsDir(), `${map.toLowerCase()}.json`);
  await writeFile(file, JSON.stringify(regions, null, 2) + "\n");
}

// Scan lib/maps/regions/*.json and regenerate index.ts. Returns count of maps wired.
export async function regenerateIndex(): Promise<number> {
  const dir = regionsDir();
  const files = (await readdir(dir))
    .filter((f) => f.toLowerCase().endsWith(".json"))
    .sort();

  const entries = files.map((file) => {
    const key = file.replace(/\.json$/i, "").toLowerCase();
    return { key, file };
  });

  const lines: string[] = [];
  lines.push(`import type { RegionPoly } from "@/lib/maps/regions";`);
  for (const { key, file } of entries) {
    lines.push(`import ${key} from "./${file}";`);
  }
  lines.push(
    `// AUTO-GENERATED by scripts/build-regions-index.ts — do not edit by hand.`,
  );
  if (entries.length === 0) {
    lines.push(`export const REGIONS: Record<string, RegionPoly[]> = {};`);
  } else {
    lines.push(`export const REGIONS: Record<string, RegionPoly[]> = {`);
    for (const { key } of entries) {
      lines.push(`  ${key}: ${key} as RegionPoly[],`);
    }
    lines.push(`};`);
  }

  await writeFile(join(dir, "index.ts"), lines.join("\n") + "\n");
  return entries.length;
}
