import type { RegionPoly } from "@/lib/maps/regions";
import ascent from "./ascent.json";
import bind from "./bind.json";
import breeze from "./breeze.json";
import fracture from "./fracture.json";
import haven from "./haven.json";
import lotus from "./lotus.json";
import pearl from "./pearl.json";
import split from "./split.json";
// AUTO-GENERATED by scripts/build-regions-index.ts — do not edit by hand.
export const REGIONS: Record<string, RegionPoly[]> = {
  ascent: ascent as RegionPoly[],
  bind: bind as RegionPoly[],
  breeze: breeze as RegionPoly[],
  fracture: fracture as RegionPoly[],
  haven: haven as RegionPoly[],
  lotus: lotus as RegionPoly[],
  pearl: pearl as RegionPoly[],
  split: split as RegionPoly[],
};
