import type { RegionPoly } from "@/lib/maps/regions";
import ascent from "./ascent.json";
import fracture from "./fracture.json";
import split from "./split.json";
// AUTO-GENERATED by scripts/build-regions-index.ts — do not edit by hand.
export const REGIONS: Record<string, RegionPoly[]> = {
  ascent: ascent as RegionPoly[],
  fracture: fracture as RegionPoly[],
  split: split as RegionPoly[],
};
