#!/usr/bin/env bash
# Regenerate viz/data.js (curated data the dashboard reads) from data/raw/*.json.
# Using a <script src="data.js"> file (rather than fetch) lets the dashboard
# open directly via file:// with no local server.
#
# Usage: ./scripts/build-data.sh [NAME]
set -euo pipefail
cd "$(dirname "$0")/.."
NAME="${1:-ST1CCS}"
RAW=data/raw

{
  echo "// AUTO-GENERATED by scripts/build-data.sh — do not edit by hand."
  printf 'window.VAL_DATA = '
  jq -n \
    --arg name "$NAME" \
    --slurpfile acc "$RAW/account.json" \
    --slurpfile mmr "$RAW/mmr.json" \
    --slurpfile hist "$RAW/mmr_history.json" \
    --slurpfile life "$RAW/lifetime.json" \
    --slurpfile matches "$RAW/matches.json" \
    '{
      account: ($acc[0].data | {name, tag, level: .account_level, region, updated_at, puuid}),
      current: ($mmr[0].data.current | {tier: .tier.name, tier_id: .tier.id, rr, last_change, elo}),
      peak:    ($mmr[0].data.peak    | {tier: .tier.name, season: .season.short}),
      seasonal: [ $mmr[0].data.seasonal[] | {act: .season.short, wins, games, end_tier: .end_tier.name} ],
      mmr_history: [ $hist[0].data.history[] | {tier: .tier.name, map: .map.name, rr, last_change, elo, date} ],
      recent_matches: [ $matches[0].data[]
        | .metadata as $m
        | (.players[] | select(.name==$name)) as $p
        | ([.teams[] | select(.team_id==$p.team_id) | .won] | (.[0] // null)) as $won
        | (($p.stats.headshots + $p.stats.bodyshots + $p.stats.legshots)) as $shots
        | {
            map: $m.map.name, mode: $m.queue.name, agent: $p.agent.name,
            kills: $p.stats.kills, deaths: $p.stats.deaths, assists: $p.stats.assists,
            score: $p.stats.score, hs: $p.stats.headshots, bs: $p.stats.bodyshots, ls: $p.stats.legshots,
            hs_pct: (if $shots>0 then ($p.stats.headshots*100/$shots) else 0 end),
            started_at: $m.started_at, won: $won
          }
      ],
      lifetime: [ $life[0].data[] | {
        map: .meta.map.name, mode: .meta.mode, agent: .stats.character.name,
        kills: .stats.kills, deaths: .stats.deaths, assists: .stats.assists, score: (.stats.score // 0)
      } ]
    }'
  echo ";"
} > viz/data.js

echo "wrote viz/data.js ($(wc -c < viz/data.js | tr -d ' ') bytes)"
