// Codegen: build a static REGIONS registry from lib/maps/regions/*.json.
import { readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

function main() {
  const dir = join(process.cwd(), "lib", "maps", "regions");
  const files = readdirSync(dir)
    .filter((f) => f.toLowerCase().endsWith(".json"))
    .sort();

  const entries = files.map((file) => {
    const key = file.replace(/\.json$/i, "").toLowerCase();
    return { key, file };
  });

  const lines: string[] = [];
  lines.push(`import type { RegionPoly } from "@/lib/maps/regions";`);
  for (const { key, file } of entries) {
    lines.push(`import ${key} from "./${file}";`);
  }
  lines.push(
    `// AUTO-GENERATED by scripts/build-regions-index.ts — do not edit by hand.`,
  );
  if (entries.length === 0) {
    lines.push(`export const REGIONS: Record<string, RegionPoly[]> = {};`);
  } else {
    lines.push(`export const REGIONS: Record<string, RegionPoly[]> = {`);
    for (const { key } of entries) {
      lines.push(`  ${key}: ${key} as RegionPoly[],`);
    }
    lines.push(`};`);
  }

  const out = join(dir, "index.ts");
  writeFileSync(out, lines.join("\n") + "\n");
  console.log(`Wired ${entries.length} map(s) into ${out}`);
}

main();
