// AUTO-GENERATED by scripts/build-data.sh — do not edit by hand.
window.VAL_DATA = {
  "account": {
    "name": "ST1CCS",
    "tag": "STONE",
    "level": 630,
    "region": "na",
    "updated_at": "2026-05-28T00:20:08.238Z",
    "puuid": "150b68cb-4440-5659-af74-e59b91a3d0a8"
  },
  "current": {
    "tier": "Ascendant 1",
    "tier_id": 21,
    "rr": 78,
    "last_change": 18,
    "elo": 1878
  },
  "peak": {
    "tier": "Ascendant 3",
    "season": "e6a2"
  },
  "seasonal": [
    {
      "act": "e1a1",
      "wins": 39,
      "games": 82,
      "end_tier": "Platinum 2"
    },
    {
      "act": "e1a2",
      "wins": 42,
      "games": 79,
      "end_tier": "Diamond 1"
    },
    {
      "act": "e1a3",
      "wins": 75,
      "games": 152,
      "end_tier": "Diamond 2"
    },
    {
      "act": "e2a1",
      "wins": 27,
      "games": 72,
      "end_tier": "Platinum 1"
    },
    {
      "act": "e2a2",
      "wins": 50,
      "games": 95,
      "end_tier": "Diamond 1"
    },
    {
      "act": "e2a3",
      "wins": 19,
      "games": 39,
      "end_tier": "Platinum 3"
    },
    {
      "act": "e3a1",
      "wins": 38,
      "games": 63,
      "end_tier": "Diamond 2"
    },
    {
      "act": "e3a2",
      "wins": 16,
      "games": 27,
      "end_tier": "Immortal 1"
    },
    {
      "act": "e3a3",
      "wins": 18,
      "games": 40,
      "end_tier": "Immortal 1"
    },
    {
      "act": "e4a1",
      "wins": 12,
      "games": 20,
      "end_tier": "Diamond 3"
    },
    {
      "act": "e4a2",
      "wins": 18,
      "games": 39,
      "end_tier": "Immortal 1"
    },
    {
      "act": "e4a3",
      "wins": 2,
      "games": 8,
      "end_tier": "Diamond 3"
    },
    {
      "act": "e5a1",
      "wins": 14,
      "games": 33,
      "end_tier": "Diamond 3"
    },
    {
      "act": "e5a2",
      "wins": 23,
      "games": 49,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e5a3",
      "wins": 18,
      "games": 37,
      "end_tier": "Ascendant 2"
    },
    {
      "act": "e6a1",
      "wins": 15,
      "games": 26,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e6a2",
      "wins": 14,
      "games": 27,
      "end_tier": "Ascendant 2"
    },
    {
      "act": "e6a3",
      "wins": 14,
      "games": 29,
      "end_tier": "Ascendant 3"
    },
    {
      "act": "e7a1",
      "wins": 20,
      "games": 41,
      "end_tier": "Ascendant 2"
    },
    {
      "act": "e7a2",
      "wins": 10,
      "games": 21,
      "end_tier": "Ascendant 2"
    },
    {
      "act": "e7a3",
      "wins": 9,
      "games": 16,
      "end_tier": "Ascendant 3"
    },
    {
      "act": "e8a1",
      "wins": 13,
      "games": 41,
      "end_tier": "Diamond 2"
    },
    {
      "act": "e8a2",
      "wins": 13,
      "games": 18,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e8a3",
      "wins": 17,
      "games": 31,
      "end_tier": "Ascendant 2"
    },
    {
      "act": "e9a1",
      "wins": 6,
      "games": 19,
      "end_tier": "Diamond 3"
    },
    {
      "act": "e9a2",
      "wins": 13,
      "games": 32,
      "end_tier": "Diamond 3"
    },
    {
      "act": "e9a3",
      "wins": 16,
      "games": 29,
      "end_tier": "Ascendant 2"
    },
    {
      "act": "e10a1",
      "wins": 10,
      "games": 19,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e10a2",
      "wins": 4,
      "games": 11,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e10a3",
      "wins": 16,
      "games": 48,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e10a4",
      "wins": 28,
      "games": 60,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e10a5",
      "wins": 25,
      "games": 62,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e10a6",
      "wins": 33,
      "games": 64,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e11a1",
      "wins": 26,
      "games": 51,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e11a2",
      "wins": 8,
      "games": 16,
      "end_tier": "Ascendant 1"
    },
    {
      "act": "e11a3",
      "wins": 5,
      "games": 8,
      "end_tier": "Ascendant 1"
    }
  ],
  "mmr_history": [
    {
      "tier": "Ascendant 1",
      "map": "Ascent",
      "rr": 78,
      "last_change": 18,
      "elo": 1878,
      "date": "2026-05-20T22:29:57.065Z"
    },
    {
      "tier": "Ascendant 1",
      "map": "Fracture",
      "rr": 60,
      "last_change": 16,
      "elo": 1860,
      "date": "2026-05-14T19:22:23.593Z"
    },
    {
      "tier": "Ascendant 1",
      "map": "Lotus",
      "rr": 44,
      "last_change": 17,
      "elo": 1844,
      "date": "2026-05-09T22:40:14.209Z"
    },
    {
      "tier": "Ascendant 1",
      "map": "Split",
      "rr": 27,
      "last_change": 15,
      "elo": 1827,
      "date": "2026-05-07T04:31:58.849Z"
    },
    {
      "tier": "Ascendant 1",
      "map": "Pearl",
      "rr": 12,
      "last_change": -19,
      "elo": 1812,
      "date": "2026-05-07T02:54:07.439Z"
    }
  ],
  "recent_matches": [
    {
      "map": "Drift",
      "mode": "Team Deathmatch",
      "agent": "Raze",
      "kills": 20,
      "deaths": 16,
      "assists": 8,
      "score": 5809,
      "hs": 14,
      "bs": 44,
      "ls": 5,
      "hs_pct": 22.22222222222222,
      "started_at": "2026-05-28T00:10:44.554Z",
      "won": true
    },
    {
      "map": "Kasbah",
      "mode": "Team Deathmatch",
      "agent": "Phoenix",
      "kills": 15,
      "deaths": 16,
      "assists": 8,
      "score": 4972,
      "hs": 14,
      "bs": 55,
      "ls": 1,
      "hs_pct": 20,
      "started_at": "2026-05-27T23:54:47.988Z",
      "won": null
    },
    {
      "map": "Corrode",
      "mode": "Swiftplay",
      "agent": "Tejo",
      "kills": 1,
      "deaths": 3,
      "assists": 1,
      "score": 285,
      "hs": 1,
      "bs": 3,
      "ls": 0,
      "hs_pct": 25,
      "started_at": "2026-05-27T05:19:02.904Z",
      "won": true
    },
    {
      "map": "Lotus",
      "mode": "Unrated",
      "agent": "Vyse",
      "kills": 9,
      "deaths": 14,
      "assists": 5,
      "score": 3076,
      "hs": 6,
      "bs": 32,
      "ls": 3,
      "hs_pct": 14.634146341463415,
      "started_at": "2026-05-27T04:37:31.51Z",
      "won": true
    },
    {
      "map": "Breeze",
      "mode": "Unrated",
      "agent": "Sova",
      "kills": 22,
      "deaths": 14,
      "assists": 4,
      "score": 6556,
      "hs": 11,
      "bs": 65,
      "ls": 2,
      "hs_pct": 14.102564102564102,
      "started_at": "2026-05-26T05:13:36.047Z",
      "won": null
    }
  ],
  "lifetime": [
    {
      "map": "Drift",
      "mode": "Team Deathmatch",
      "agent": "Raze",
      "kills": 20,
      "deaths": 16,
      "assists": 8,
      "score": 5809
    },
    {
      "map": "Kasbah",
      "mode": "Team Deathmatch",
      "agent": "Phoenix",
      "kills": 15,
      "deaths": 16,
      "assists": 8,
      "score": 4972
    },
    {
      "map": "Corrode",
      "mode": "Swiftplay",
      "agent": "Tejo",
      "kills": 1,
      "deaths": 3,
      "assists": 1,
      "score": 285
    },
    {
      "map": "Lotus",
      "mode": "Unrated",
      "agent": "Vyse",
      "kills": 9,
      "deaths": 14,
      "assists": 5,
      "score": 3076
    },
    {
      "map": "Breeze",
      "mode": "Unrated",
      "agent": "Sova",
      "kills": 22,
      "deaths": 14,
      "assists": 4,
      "score": 6556
    },
    {
      "map": "Kasbah",
      "mode": "Team Deathmatch",
      "agent": "Phoenix",
      "kills": 25,
      "deaths": 12,
      "assists": 7,
      "score": 7115
    },
    {
      "map": "Piazza",
      "mode": "Team Deathmatch",
      "agent": "Raze",
      "kills": 22,
      "deaths": 18,
      "assists": 10,
      "score": 6934
    },
    {
      "map": "District",
      "mode": "Team Deathmatch",
      "agent": "KAY/O",
      "kills": 24,
      "deaths": 12,
      "assists": 14,
      "score": 6770
    },
    {
      "map": "Bind",
      "mode": "Unrated",
      "agent": "Phoenix",
      "kills": 11,
      "deaths": 9,
      "assists": 3,
      "score": 2836
    },
    {
      "map": "Glitch",
      "mode": "Team Deathmatch",
      "agent": "Phoenix",
      "kills": 16,
      "deaths": 20,
      "assists": 5,
      "score": 4709
    }
  ]
}
;
